version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:latest
    container_name: nest-graphql-db
    volumes:
      - db-data:/var/lib/postgresql/nest-graphql-db/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password